import React from "react"

const pro=[
    {
    id:1,
    product_Name: 'GREEN Tea',
    type:'GREEN TEA',
    brand: 'Bambi' ,
    qty: '250g',  
    price: 250,
    image: 'images/GT_1.jpg',
    image1: 'images/tea_cup.jpg',
    image2: 'images/GT_1.jpg',
    image3: 'images/GT_1.jpg',
    },
    {
    id:2,
    product_Name: 'CTC Tea',
    type:'CTC TEA',
    brand: 'Bambi' ,
    qty: '250g',
    price: 250,
    image: 'images/tea_cup.jpg',
    image1: 'images/shopping-cart.png',
    image2: 'images/Chai_1.jpg',
    image3: 'images/GT_1.jpg',

    },
    {
        id:3,
        product_Name: 'CTC Tea',
        type:'GREEN TEA',
        brand: 'Bambi' ,
        qty: '250g',
        price: 250,
        image: 'images/tea_cup.jpg',
        image1: 'images/tea_cup.jpg',
        image2: 'images/GT_1.jpg',
        image3: 'images/GT_1.jpg',
        },
        {
            id:4,
            product_Name: 'CTC Tea',
            type:'CTC TEA',
            brand: 'Bambi' ,
            qty: '250g',
            price: 250,
            image: 'images/tea_cup.jpg',
            image: 'images/tea_cup.jpg',
            image1: 'images/shopping-cart.png',
            image2: 'images/Chai_1.jpg',
            image3: 'images/GT_1.jpg',
            }, {
                id:5,
                product_Name: 'CTC Tea',
                type:'CTC TEA',
                brand: 'Bambi' ,
                qty: '250g',
                price: 300,
                image: 'images/tea_cup.jpg',
                image: 'images/tea_cup.jpg',
                image1: 'images/tea_cup.jpg',
                image2: 'images/GT_1.jpg',
                image3: 'images/GT_1.jpg',
                },
                {
                    id:6,
                    product_Name: 'CTC Tea',
                    type:'CTC TEA',
                    brand: 'Bambi' ,
                    qty: '250g',
                    price: 250,
                    image: 'images/tea_cup.jpg',
                    image1: 'images/shopping-cart.png',
                    image2: 'images/Chai_1.jpg',
                    image3: 'images/GT_1.jpg',
                    }
]

export default pro